### ISSUE TITLE
FS-i6 with TGY-CAT01

### ISSUE THREAD

**Issue by cookieqk** [qba667/FlySkyI6#10]
Hi,
Looks like there's ZERO owners & users of turnigy's altitude sensor... 
 I've connected it to FS-iA6b receiver.  On sensors list in my FS-i6 with he last MOD (14_channels_SWE) there's just a "Pressure sensor". It shows 9 digits on the screen e.g 367123788. There's no possibility to change unit (Pa, psi, bar... ) or to do anything else with it.

From hobbyking: "Reliably monitor the altitude of your model with the TGY-CAT01 Altitude Sensor for use with the TGY-iA10 receiver and TGY-i6 transmitter. Use it to measure the real-time altitude of your drone, plane or heli directly on your Turnigy i10 transmitter."

I even updated my FS with Turnigy's TGY-i6 firmware, but it still hadn't work correct.

Is it possible, that connecting CAT01 to FS(TGY)-iA10(B?) receiver would change anything?

**Comment by qba667** [comment]
@cookieqk there is typo in HobbyKing description - I have guessed the format of the sensor because I don't have one. There is code base prepared to handle the sensor but it is not fully enabled. Maybe I will enable it in future - depending on resources.

**Comment by cookieqk** [comment]
@qba667 = Jakub => POL? :-)

**Comment by qba667** [comment]
@cookieqk your reasoning seems to be correct;)

**Comment by qba667** [comment]
@cookieqk  the CAT01 damaged my IA6B. But I get some log entries:
![ac](https://user-images.githubusercontent.com/3341647/29093836-83354282-7c8b-11e7-87a9-e2fd5f776d75.png)

**Comment by cookieqk** [comment]
This is not very good news :-/ My iA6b works fine with cat01 - theoretically...

**Comment by JakubMichal** [comment]
Hi. Anything new about this Cat01?

**Comment by qba667** [comment]
@JakubMichal 
it is almost working some small improvements are needed.

**Comment by JakubMichal** [comment]
You are the best! ;-)

**Comment by qba667** [comment]
@JakubMichal @cookieqk
It is done! It took a lot of flash space - but seems to be working. It could be used as ASL and relative value. 
https://github.com/qba667/FlySkyI6/releases/tag/1.7.1
Have a lot of fun!
@cookieqk thank you very much for your support.  
Wysokich lotów panowie

**Comment by qba667** [comment]
@JakubMichal @cookieqk 
As bonus you can use vario functionality to get notifications about value change.

**Comment by JakubMichal** [comment]
Super! Thank you very much! ;-)

**Comment by qba667** [comment]
No complains  == working solution. Closing.
