### ISSUE TITLE
No SWE found after update FLYPLUS 1.7.6

### ISSUE THREAD

**Issue by louisFpv** [qba667/FlySkyI6#101]
Thx your contribution for the new firmware 1.7.6.

I have updated the new firmware 1.7.6 but no swe found in aux channels no matter which bin file fs-i6-swe_updater_05_07_12_30, or fs-i6_updater_05_07_12_30 installed. My i6 was already updated to 1.7.5 before and mod swb and swe, it works ok and good. 
Would you like to check it whether the SWE bin file is missed or right?

Thx & regards

**Comment by Yenya** [comment]
@louisFpv, can you test the attached firmware file?
[swe-test.zip](https://github.com/qba667/FlySkyI6/files/4689465/swe-test.zip)
It might be that the firmware got built incorrectly.

**Comment by louisFpv** [comment]
Thx, SWE presents again. Well Done




![WhatsApp Image 2020-05-28 at 00 14 17](https://user-images.githubusercontent.com/38834826/83045837-bcaa0480-a078-11ea-9697-aa504f42f7a5.jpeg)
![WhatsApp Image 2020-05-28 at 00 10 19](https://user-images.githubusercontent.com/38834826/83045856-c3d11280-a078-11ea-988f-922b40a692b1.jpeg)

**Comment by Yenya** [comment]
OK, thanks for the bug report and for testing this. I have replaced the SwE firmware in the 1.7.6 relase zip archive with the above one.
