### ISSUE TITLE
[INFO] You can flash the firmware using an Arduino with an FTDI chip.

### ISSUE THREAD

**Issue by TheUNkilled123** [qba667/FlySkyI6#104]
Not an issue, but I just discovered that you can flash it using Arduinos if you don't have the programmer. You do need an arduino with an FTDI chip, not the CH340 chip. I tried with my UNO clone, but it had the CH340, so the flashing program just crashed. I also tried my pro micro(also clone) and the same thing happened. Then I remembered I had a nodeMCU wifi arduino based board and tried that one. Worked like a charm. You can follow this tutorial for the wiring, after you wire it up, all you need to do is normally launch the flashing program and pick the correct port(you can find the port in device manager).
Wiring tutorial link: https://www.youtube.com/watch?v=LfZHrCZyC6o

**Comment by Yenya** [comment]
@TheUNkilled123: Thanks, I have added this to the Install page in Wiki:
https://github.com/qba667/FlySkyI6/wiki/Install#flashing-with-arduino
