### ISSUE TITLE
 I ask for a hint on how to create a custom firmware =) is it possible?

### ISSUE THREAD

**Issue by maxtwin048** [qba667/FlySkyI6#109]
hi, please tell me there is more information on compiling the firmware? I can't figure out how to do it =) is it possible?

**Comment by Yenya** [comment]
Please have a look at the Development page in the Wiki:

https://github.com/qba667/FlySkyI6/wiki/Development 

I have just extended it somewhat more.

**Comment by maxtwin048** [comment]
**Thank you very much**  @Yenya
