### ISSUE TITLE
 Help with compiling the firmware (((

### ISSUE THREAD

**Issue by maxtwin048** [qba667/FlySkyI6#112]
Help me understand what the compilation problem is and what "Error 1" means? 

Please, Help GREAT GURUS @qba667 @Yenya @gh05t88 @unitware @hali9 

![33334444](https://user-images.githubusercontent.com/57296897/90451897-9040da00-e0f5-11ea-928d-d1c54c0ea8f3.gif)

![Снимок экрана 2020-08-18 в 01 44 55](https://user-images.githubusercontent.com/57296897/90451779-3fc97c80-e0f5-11ea-9446-981bf21ec071.png)

**Comment by Yenya** [comment]
@maxtwin048 - it is explained in the documentation: https://github.com/qba667/FlySkyI6/wiki/Development
You made the code bigger (in the .mod_code_E140_E754 section) and it does not fit between 0xE140 and 0xE754.

Also, the Issues in this repo are not meant as a help system - they are for reporting bugs and problems. If help is needed, you can for example join the rcgroups thread mentioned in the front page.

**Comment by qba667** [comment]
@maxtwin048 Probably caused by compiler, we are using version 4.9.3. This one for sure will compile not changed code.

**Comment by Yenya** [comment]
FWIW, I use arm-none-eabi-gcc-cs-9.2.0-4.fc32.x86_64, arm-none-eabi-binutils-cs-2.32-3.fc32.x86_64, and arm-none-eabi-newlib-3.1.0-4.fc32.noarch. But yes, different toolchain versions can lead to different code segment sizes.
