### ISSUE TITLE
 Is it possible to get open source 1.7.5?

### ISSUE THREAD

**Issue by maxtwin048** [qba667/FlySkyI6#114]
Is it possible to get open source **1.7.5**?  Thank you very much guys!!!  **All old firmwares are compiled**, but the latest firmware does not compile

**Comment by maxtwin048** [comment]
@Yenya Please Help 😭

**Comment by maxtwin048** [comment]
@qba667 please help 😭😭😭

**Comment by Yenya** [comment]
I think fast_telemetry corresponds to the commit  # 26b030248543b91bc67320bd0f50e7b59e0ba084.
Anyway, what problems do you have with compiling the current master?

**Comment by maxtwin048** [comment]
@Yenya 



this is what I get while compiling the master(
![Снимок экрана 2020-09-14 в 23 50 29 1](https://user-images.githubusercontent.com/57296897/93137064-95d61380-f6e5-11ea-8a81-5672eafe371f.png)

**Comment by maxtwin048** [comment]
but 1.7.5 compiles without problems.

but 1.7.5 compiles without problems. but telemetry is slow. I cannot find the telemetry update values ​​((( Help please @Yenya

**Comment by Yenya** [comment]
As the linker says, the compiled section overlaps with the protected section from the original firmware. Maybe use a different compiler version or use -Os switch to force the compiler to make smaller code? In my compiler the section fits the assigned size. Or you can edit the linker script (MKL16Z64xxx4_flash.ld) and assign some functions to the other address blocks.

**Comment by maxtwin048** [comment]
@Yenya 
[FlySkyI6-1.7.5.tar.zip](https://github.com/qba667/FlySkyI6/files/5301443/FlySkyI6-1.7.5.tar.zip)

 , could you help me, and speed up the telemetry update in this particular firmware? I will be very grateful to you) Thank you very much !!!
the original code from the repository which compiles for me without problems, below)

**Comment by jan5650** [comment]
I had the same problem :(

![error](https://user-images.githubusercontent.com/71666503/98222625-5db6b880-1f51-11eb-85a0-b8b225afe35c.JPG)

When i compile the last firmware, i get this error...

When i use "make -i all" then it's finish, but i don't know its good?

Another Question: when its finished i get a .map file. How can i get a .bin from this? Thank you!

**Comment by Yenya** [comment]
I believe the original question has been answered in the first comment, so I am closing this issue.
