### ISSUE TITLE
Potentiometers

### ISSUE THREAD

**Issue by Rom4ik-glitch** [qba667/FlySkyI6#117]
Is it possible to change all the switches to the potentiometers?

**Comment by Yenya** [comment]
No. some of the switches are connected to digital-only pins. SwB and SwC can do analog, SwA, SwD, and SwE cannot.

**Comment by Rom4ik-glitch** [comment]
okay, is it possible to use 3-positional switch at swa and swd channels?

**Comment by Yenya** [comment]
No, as I said, those pins are digital-only.

**Comment by Rom4ik-glitch** [comment]
Well, thanks)
