### ISSUE TITLE
new X6B - not binding !

### ISSUE THREAD

**Issue by yo8aiv** [qba667/FlySkyI6#12]
hello, anyone had this problem >>??

new X6B - not binding ! tried ppm and ibus and nothing 
receiver is blinking but binding not happening.
Thanks.

**Comment by yo8aiv** [comment]
after further tests i managed to bind the X6B this way:
- supply from a rs232/ftdi adapter 5V 
- going into the secret menu, see here 
![adv menu](https://user-images.githubusercontent.com/24196117/28987185-83dd17ec-796a-11e7-99b9-42373707f2db.jpeg)

its weird that it didn't work the usual binding way - with the bind key - is that a known bug ??!!

**Comment by qba667** [comment]
@yo8aiv are you using FW from my (this) repository? Older version has a bug related to binding?

**Comment by yo8aiv** [comment]
Thanks for the fast answer.
Well if i remember well primarily i think i downloaded this firmware from rcgroups page not from here directly.
after i have found the repository -- wasnt easy .. and downloaded this one ,, but i'm not shure i flashed this latest version.
i'll try reflashing this one and see how it behaves and i'll get back 

this one i 've flashed https://www.rcgroups.com/forums/showatt.php?attachmentid=10192248&d=1499865537

**Comment by qba667** [comment]
The bug was known in this version - use latest one from repository.

**Comment by yo8aiv** [comment]
OK. Thanks.
Flashing.

**Comment by yo8aiv** [comment]
Done. Works.
Its nice you've added information on the firmware page regarding moded version. 
Cheers. see my other proposal about flashing alarm on screen text.
Thx again.
