### ISSUE TITLE
channel 1-6, end points can only be set for the left half

### ISSUE THREAD

**Issue by mindquest111** [qba667/FlySkyI6#122]
in 1.7.6, i try to set up end point for channel 1-6, when i use OK to scroll to ending point setting, it only allow me to scroll (select) the left half of the end point settig, it does not scroll to the right half, which means i can only set the end point for only 1 end of each channel. is this a known problem? is there any work around？ help!

**Comment by Yenya** [comment]
This is not a feature of FlyPlus, it is the same in the stock firmware: you have to move the channel input itself (i.e. the stick, switch or potentiometer) to the other half of its range - then the endpoint setup switches to the other end and you can adjust it.

**Comment by mindquest111** [comment]
thank u. got it. now i feel like, duh... me
