### ISSUE TITLE
reversed gimbals after flashing

### ISSUE THREAD

**Issue by lidorshimoni** [qba667/FlySkyI6#127]
the gimbals (channels 1-4) are reversed, even at startup when it warns to place all switches in their up position and **throttle down**, I need to place all switches in their up position and **throttle up**! I'm currently just using the remote with all 4 channels inverted to fix it but it's still pretty annoying. did I do something wrong? am I the only one who had this problem?

**Comment by 8jigarpatel** [comment]
Give this a try maybe?
[https://www.youtube.com/watch?v=FkJRcjszEd8&ab_channel=-Mirek-](https://www.youtube.com/watch?v=FkJRcjszEd8&ab_channel=-Mirek-)

**Comment by lidorshimoni** [comment]
> Give this a try maybe?
> https://www.youtube.com/watch?v=FkJRcjszEd8&ab_channel=-Mirek-

tried it. didn't work. the sticks are still reversed.

**Comment by Yenya** [comment]
Hi, I have just flashed a newly-bought FS-i6 to FlyPlus 1.7.6 (as released), and do not see this behaviour. That is not to say your issue does not exist, but I wonder what hardware difference there can be between yours FS-i6 and at least 6 FS-i6 I have flashed so far.

**Comment by lidorshimoni** [comment]
Yeah it does sound really weird. 
I guess I’m the only one and it’s not related to the firmware.
I fixed it by switching the wires of the pots.
