### ISSUE TITLE
1.7.5 fast telemetry

### ISSUE THREAD

**Issue by jan5650** [qba667/FlySkyI6#135]
**Hi!**

Do you added fast telemetry update for 1.7.5 version. (named 1.7.5_Fast_telemetry.zip)
Sadly i cannot compaile the 1.7.6 version, because complaier mismatch, so i need to use the 1.7.5 version.

**My questin**: is there any changes in **Ibus Telemetry speed** between 1.7.5 fast telemetry and 1.7.6 ?
I am only focused on the refresh speed of Telemetry...

Or can i use the simple 1.7.5 and write this changes into the source files?:
(https://github.com/qba667/FlySkyI6/commit/26b030248543b91bc67320bd0f50e7b59e0ba084)

Edit: Just see, that the 1.7.5 fast telemetry update's sources files didin't published. Can you publish it please? 

Thank you!

**Comment by Yenya** [comment]
@jan5650  - you can do "git log" and display all the commits between 1.7.5 and HEAD. Some of them should describe the fast telemetry update.

Also, can you test whether the current HEAD (863819f) compiles with your toolchain?

**Comment by jan5650** [comment]
"Also, can you test whether the current HEAD (863819f) compiles with your toolchain?"

Maybe if I Reorder linking as you mentonied then i can compile the 1.7.6 with newer GCC?
That would be great!

**Comment by jan5650** [comment]
Dear Yenya!

With moving .mod_auxChannelsText to the very end of the code in the firmware lines it's work Great!!
Now i can compile the latest 1.7.6. firmware with no problem!

Thank you!
