### ISSUE TITLE
Problems with firmware editing

### ISSUE THREAD

**Issue by Bananchik312** [qba667/FlySkyI6#144]
Hello.

I am trying to add my code to alt.c, void display Sensor(), but judging by the compiler output, either my code takes up too much space, or there is too little free space in this section. I tried to reduce .reserved_after_code_65c8_68a7, and after that the compiler compiled the firmware without errors, but after downloading the firmware to the remote, I saw that when I tried to open the menu, my flysky i-6 beeps and reboots. 

Here is the error that the compiler gives me:
/usr/lib/gcc/arm-none-eabi/9.2.1/../../../arm-none-eabi/bin/ld: section .reserved_after_code_65C8_68A7 LMA [00000000000068a8,00000000000068ab] overlaps section .mod_code_65C8_68A7 LMA [00000000000065c8,00000000000068bf]
collect2: error: ld returned 1 exit status
make: *** [makefile:71: fsi 6.elf] Error 1

**Comment by Yenya** [comment]
The reserved_after_... section is, well, reserved. It contains code we do not mess with, and you shouldn't either. Yes, in FS-i6, the memory is extremely tight. You can play with the linker setup and for example put some routines to other sections.

**Comment by Bananchik312** [comment]
Yenya, hello 
Unfortunately, I couldn't solve the problem myself. If it's not too much trouble, I want to ask you for help.
I add a few lines to the alt.c file in the display Sensors function. But the big problem becomes that then the .mod_code_65C8_68A7 section overlaps the .reserved_after_code_65C8_68A7 section. Can you tell me what I need to do so that my code fits and I can build the firmware?

(sorry for my English, I'm from Russia)

**Comment by Bananchik312** [comment]
> The reserved_after_... section is, well, reserved. It contains code we do not mess with, and you shouldn't either. Yes, in FS-i6, the memory is extremely tight. You can play with the linker setup and for example put some routines to other sections.

Yenya, hello
Unfortunately, I couldn't solve the problem myself. If it's not too much trouble, I want to ask you for help.
I add a few lines to the alt.c file in the display Sensors function. But the big problem becomes that then the .mod_code_65C8_68A7 section overlaps the .reserved_after_code_65C8_68A7 section. Can you tell me what I need to do so that my code fits and I can build the firmware?

(sorry for my English, I'm from Russia)

UPD: If I understood correctly, my code occupies 44 bytes (324 bytes (0x144) were occupied by an unchanged function, 268 (0x170) bytes are occupied by a function with the code I added)
