### ISSUE TITLE
make GFX editor multiplatform and share the sources

### ISSUE THREAD

**Issue by sl1pkn07** [qba667/FlySkyI6#15]
Hi

is possible make the GFX editor multiplatform?

where can download the sources?

not all people use windows system ;)

greetings

**Comment by qba667** [comment]
@sl1pkn07 
The editor has been written in c# if mono is fine for you I can provide the source.

**Comment by sl1pkn07** [comment]
mono can work natively on linux. but i'm not sure if the code of gfx editor is windows centric

**Comment by qba667** [comment]
It is not:) you will need just one method to create byte array from bitmap.

**Comment by qba667** [comment]
@sl1pkn07 here you have the source:
https://github.com/qba667/FlySkyI6/tree/master/GFXeditor

**Comment by sl1pkn07** [comment]
tnx!

**Comment by sl1pkn07** [comment]
what you mean with this?

> It is not:) you will need just one method to create byte array from bitmap.

anyway. i can compile the code with mono 5.0.0 (provided by package distro) with `xbuild`

greetings

**Comment by qba667** [comment]
I meant  the gfx editor is not windows centric. 
Great, you can share the binary.

**Comment by sl1pkn07** [comment]
done 

https://github.com/sl1pkn07/FlySkyI6/commit/97da338baccb7a01f82092bb33a557d6b11cff0e

**Comment by sl1pkn07** [comment]
update https://github.com/sl1pkn07/FlySkyI6/commit/44b590b118f60a65d711518fae9db3488c30615e

NOTE: for only x86_64
