### ISSUE TITLE
Settings not saving

### ISSUE THREAD

**Issue by NosajRellim** [qba667/FlySkyI6#157]
I just updated from the factory version 1.1 25-NOV-2014 to FlyPlus 1.7.5 and 1.7.6 and in both versions the aux channels along with other settings are not saving.  I enter the aux channels sub menu, change any Channel 5-14 to SwA, exit the Aux Channel sub menu by pressing cancel.  When I enter the Aux Channel sub  menu the settings are reset back to the original settings.  I am sure I am doing something wrong but I do not know what.  Please advise.

**Comment by Yenya** [comment]
Hello, in FS-i6 (even in the factory firmware), saving is done by long-pressing the Cancel button. Short Cancel just reverts the modifications and restores the previously saved values. However it is counter-intuitive, we decided to respect this even for menus we added.

Hope this helps,

-Yenya

**Comment by NosajRellim** [comment]
You are absolutely right.  I feel incredibly dumb I did not know this.
Thank you for your help!
