### ISSUE TITLE
Cannot install update using FS-SM100 USB dongle

### ISSUE THREAD

**Issue by MikeVitik** [qba667/FlySkyI6#160]
I have [USB dongle](https://www.amazon.com/RCmall-Simulator-Adapter-FS-TH9X-Controller/dp/B01AAETLVY) based on FS-SM100 chip. The cable works fine and I don't have any problem with it (it appears in the system as a joystick device).  But the upgrade firmware using then the last version doesn't work. I suppose the problem is the proper driver for FS-SM100.  Or maybe FS-SM100 isn't USB-to-RS232 compatible.
Can you give me some advice for future steps to find an issue of the problem?

**Comment by mzashh** [comment]
![Screenshot_20230621-205154_eBay](https://github.com/qba667/FlySkyI6/assets/58217787/8ddb9c57-4103-4e0d-80be-6c378e391486)
that cable one is used for sending data, you can see that its pin has only 2 sections RX and Ground, just use USB to serial adapters, ch340, cp2102 etc it should work fine also make sure the radio is in update mode (holding the 2 trim buttons during power up), and also when using the USB to serial adapters make sure that the wiring is correct and its set to 3.3v
