### ISSUE TITLE
Feature: Display Backlight Time

### ISSUE THREAD

**Issue by DimaVIII** [qba667/FlySkyI6#19]
Hey,

It will be one of the best features if there will be a option set the time of the display backlight.
It's a shame to have telemetry on the transmitter and to be forced to push ever 20 sec a button to see this.
I understand it might be a lot of work.
May instead:
Can you just publish a version where the backlight never turns off.

**Comment by qba667** [comment]
@DimaVIII it should be 2 byte change, I will provide the offset to be changed.

**Comment by DimaVIII** [comment]
@qba667 thank you! Looking forward to it!

**Comment by qba667** [comment]
@DimaVIII I got working radio back - I will search for place to be changed.

**Comment by qba667** [comment]
@DimaVIII 
Addressed in full image with boot-loader, if you are using updater image substrac 0x18
Timout is stored at the address 0x2BD8 -> 20 4E 00 00 = 4E20 Increase this one
Call turning of back light is located at 0x286E -> 03 F0 11 FA replace by nops C0 46 C0 46
