### ISSUE TITLE
SW E assign as throtle hold

### ISSUE THREAD

**Issue by pavelkonir** [qba667/FlySkyI6#23]
It is possible to set switch E as throtle hold?

**Comment by alandroid** [comment]
And is it possible to make SwE 3-position instead of 2-position like SwB?

**Comment by Yenya** [comment]
@pavelkonir: no, SwE can currently be only set as a channel source, not to any special purpose
(DR/Expo, Teacher/Student, Thr hold, ...).

@rocketkittens: no, SwE is connected to the digital pin of the MCU, so it is inherently two values only.
