### ISSUE TITLE
model memory

### ISSUE THREAD

**Issue by gazeddy** [qba667/FlySkyI6#32]
is it possible to recover the model memory before i flash. i have a couple of multirotors with depinned ia6b receivers that are encased in epoxy with only three wires coming out. so have no way of rebinding them without risking damage.

**Comment by qba667** [comment]
@gazeddy 
Theoretically we can send them over UART. But to do it you need to flash custom firmware:)
The other way is read I2C eeprom. I have use method described here:
https://www.richud.com/wiki/Rasberry_Pi_I2C_EEPROM_Program

**Comment by qba667** [comment]
@gazeddy depending how old current firmware is:)

**Comment by gazeddy** [comment]
as far as im aware its the original version so not holding my breath on it. thanks for your help
