### ISSUE TITLE
flysky i6x

### ISSUE THREAD

**Issue by jmvau54** [qba667/FlySkyI6#34]
Hi
I have a question that I don't find answser

Is your firmware compatible with flysky i6x ? or not ?

Thank you for your answer.

**Comment by lrusnac** [comment]
@jmvau54 it is not compatible, the i6x has different hardware from i6

**Comment by qba667** [comment]
@lrusnac that is true, but firmware is similar same rules, similar methods. 
Lately my code evolved a little so maybe it could be code base for I6X as well. Someone must invest time in disassembly, personally I like STM much more than Freescale. There is much more resources - things are just easier. Working on next device would be much simpler. However the best solution would be to rewrite whole firmware. We know protocol or some parts of protocol there is still a lot of magic that is present in IA6B which I am not able to understand. At lest approach can be applied - maybe someone one day will try.

**Comment by lrusnac** [comment]
@qba667 that's interesting, I would like to see a port for the i6x, but I think the answer to his question is "No" because you can't just upload the current firmware to the i6x

**Comment by jmvau54** [comment]
Hi
Thanks
Do you know an alternative firmware for i6x ?
I have a th9x with er9x. With it, I can do all I want. 
I have bought an i6x to use wirh boat, car and digger. But programming is very poor.
I would buy an i6.

**Comment by qba667** [comment]
@jmvau54 no one that I aware of - they were rumors about OpenTX. FlySky contacted bsongis from open TX, they promise resources and sources but no feedback so far.

**Comment by qba667** [comment]
@jmvau54 We decided to create port for I6X. Please see:
https://gogetfunding.com/flyplus-firmware-for-flysky-i6x/

**Comment by jmvau54** [comment]
Great news 
thank you
