### ISSUE TITLE
Explain how the channel 11-14 are used

### ISSUE THREAD

**Issue by alandroid** [qba667/FlySkyI6#35]
The documentation should include a section that explains how to use the extra channels, perhaps a quick youtube video?

Please, thank you.

**Comment by qba667** [comment]
You probably need to configure max channel number:
Try in CLI:
get max_aux_channels
max_aux_channels = 14
Allowed range: 0 - 14

if different then use:
set max_aux_channels = 14

**Comment by qba667** [comment]
Verified - nothing to be done from my perspective.

**Comment by alandroid** [comment]
Better/more documentation to be done to lessen issues raised.
