### ISSUE TITLE
Vario support !!! - telemetry based ?!!?

### ISSUE THREAD

**Issue by yo8aiv** [qba667/FlySkyI6#36]
Vario support !!! - telemetry based (i suppose)?!!? 
Can this be done. it would be interesting for planes/gliders.

Nice work. Again.
Cheers.

**Comment by qba667** [comment]
@yo8aiv - vario already implemented using sensor data - all credits for this to @Yenya.

**Comment by yo8aiv** [comment]
Great. Thanks.
How do we activate ?/!

**Comment by Yenya** [comment]
Just connect any altitude or pressure sensor to your Rx, and in the Extra->Vario submenu select that sensor and set up a gain for it. I use an altitude sensor which reports altitude in 4 bytes in centimeters (AFAIK), and use gain 5.

**Comment by yo8aiv** [comment]
very nice.
Thanks for the great addition. 
Cheers.
