### ISSUE TITLE
Image #1 change bricks the transmittter.

### ISSUE THREAD

**Issue by koevoetsfjm** [qba667/FlySkyI6#38]
NO-SWE version 1.71:

If you replace the first image (THE AFHDS2A image, which looks garbled in the graphics editor) you will brick your FS-i6 after upgrade. The display stays blank and the backlight turns on / off. I think it's due to the timer beeing displayed in that position. 

I don't know if that's fixable or not, but might be wise to add it to the readme.

I was able to fix it by holding the left-hand trimbuttons to right/down and turn the radio on, then re-flashing the untouched 1.71.

Background info: 
This image:
![afhda logo](https://user-images.githubusercontent.com/12787382/34110842-253f9102-e408-11e7-9af1-e1ef1b1557bc.png)

looks like this in the GFX editor:  ![fs-i6_updater_12_11_19_39](https://user-images.githubusercontent.com/12787382/34110910-609917fa-e408-11e7-935a-b0e572696ec0.png)  I thought it was a bad image, so i tried to replace it with the one above.
The resulting firmware bricked my transmitter after upload.

**Comment by qba667** [comment]
As you probably seen there is no more AFHDS logo any more in the firmware. The space have been used for storing code. GFX editor has hard-coded offsets of images - and allows selection - but user is responsible for changes - because address can be provided so I don't care. 
So please do not change something that doesn't look like a image.

**Comment by koevoetsfjm** [comment]
Yup, i noticed. It's no problem, but maybe worth a note ;-)

thx for your efforts, i'm really enjoying this firmware!

**Comment by qba667** [comment]
@koevoetsfjm thanks, there is one more (probably last) update coming allowing sub-trim and endpoints on all channels.
