### ISSUE TITLE
Received packet beep

### ISSUE THREAD

**Issue by diegotagoz** [qba667/FlySkyI6#41]
Is there a way to turn off the continious beep that sounds when is a receiver connected? I supose it's because uf incoming packets, but it's stressful... Thanks

**Comment by qba667** [comment]
@diegotagoz check telemetry alarms  - I will change default configuration in feature to avoid it.

**Comment by qba667** [comment]
@diegotagoz configure Vario to none - it should help. Version 1.7.3 should have this fixed.
