### ISSUE TITLE
Sticks Mode not working

### ISSUE THREAD

**Issue by JensBoerner** [qba667/FlySkyI6#49]
Having updated to latest release 1.7.5 (First with the CLI updater, then with the GUI) I am experiencing a problem with the startup. Throttle needs to be up, not down, it seems to be reversed. Also Whatever Stick Mode I choose, Channel 3 is always on the Throttle lever.

**Comment by JensBoerner** [comment]
Update: In Mode2 it starts up with stick to the bottom, I noticed after a factory reset.

Btw. Would it be possible to add Channebl 7+ to the Mix and Reverse Menus?

**Comment by qba667** [comment]
@JensBoerner Reverse for sure. But for mix hard to say because those methods are somewhere deep in original firmware.

**Comment by qba667** [comment]
@JensBoerner maybe it will be possible to add those channels to mix as well - I will create test build.

**Comment by qba667** [comment]
Working exactly as in stock firmware.
