### ISSUE TITLE
Quad icon !

### ISSUE THREAD

**Issue by yo8aiv** [qba667/FlySkyI6#5]
Would be nice to have an quadcopter icon instead of plane.
Thx.

**Comment by jordirafel** [comment]
+1 or a custom load image 💃

**Comment by jordirafel** [comment]
![quad](https://user-images.githubusercontent.com/26739482/28205380-0b619a84-6882-11e7-8b0e-5c232aa68638.png)

**Comment by qba667** [comment]
@jordirafel perfect! I will add this one in place of current one!

**Comment by qba667** [comment]
Or maybe I will write small app to change the icon to custom one.

**Comment by yo8aiv** [comment]
great !

**Comment by qba667** [comment]
@yo8aiv, @jordirafel I will add method to load custom PNG into updater so you can load whatever you want.

**Comment by jordirafel** [comment]
Great! Many thanks

**Comment by qba667** [comment]
@jordirafel, @yo8aiv GFX editor added:
https://github.com/qba667/FlySkyI6/releases/download/1.6.3/FW.gfx.editor.zip
Learn how to use it and write some documentation.

**Comment by jordirafel** [comment]
This is awesome, its possible to change other icons too! Many thanks :)

**Comment by yo8aiv** [comment]
thanks. in progress.
