### ISSUE TITLE
Afhds / afhds2 lock up

### ISSUE THREAD

**Issue by Whitey2505** [qba667/FlySkyI6#50]
Excellent work on the firmware.
There's so much information in so many places that this may have been highlighted already if so my apologies.
Are you aware that when you try to change receiver type from AFHDS2 to AFHDS,
 as soon as you set AFHDS2 to off the TX locks up (no button selections register at all) and you have to turn the TX off and back on to unlock it?

Thanks again for the hard work 👍👏👏👏

**Comment by qba667** [comment]
@Whitey2505 
I was not aware about it - thanks for info - I will try to check it. Is the value saved?

**Comment by Whitey2505** [comment]
No, value isn't saved so you can't switch out of AFHDS2. You can't back out of the menu either. As soon as you set it to off the TX locks up.

**Comment by qba667** [comment]
@Whitey2505 just verified against latest FW. I can not reproduce the issue. Can you provide more details about your setup?

**Comment by Whitey2505** [comment]
Yeah, absolute standard TGY-I6.
I'll try it again to be certain but did it twice yesterday.

**Comment by Whitey2505** [comment]
Really wierd, that worked fine this time. Put it down to user error I guess. Thanks again 👍

**Comment by qba667** [comment]
Okey, if this occurs again let me know - we will trace it and fix it.
