### ISSUE TITLE
Where can I find the figure of SWE?

### ISSUE THREAD

**Issue by hwdz** [qba667/FlySkyI6#53]
I remembered there is a figure of SWE on github some days ago, But now I can't find it.
The figure shows the Postion of  "Unnamed Test Point".
Now it disspeared.

**Comment by qba667** [comment]
@hwdz 
On Release page - under version 1.6
https://user-images.githubusercontent.com/3341647/27988798-cecf755a-642b-11e7-93a1-aed15b4cf2ec.png
https://user-images.githubusercontent.com/3341647/27991797-5bb49bf2-6482-11e7-8936-60a8141bc104.jpg

**Comment by hwdz** [comment]
Thank you!  I have searched it for a week!
