### ISSUE TITLE
end points (calibration) not working

### ISSUE THREAD

**Issue by Blakinas** [qba667/FlySkyI6#54]
It meant, that if i go to the Menu, then go to the Functions setup, then go end points. with up donw keys you can adjust 100% to 99 or to 101%. with the Ok button you can jump to the next value. but seams, that it jums randomly, not to the next value.
If you need more comments, please write to me email tomas.sliauteris@gmail.com

**Comment by qba667** [comment]
@Blakinas endpoint for channels 1-6 are using FlySky configuration. The OK button jumps only on minimum value. To change maximum value when the channel is selected you need to trigger high value (move stick, or switch the switch). Endpoint for channels 7-14 are using indeed OK button for navigation.
Please see come tutorials on youtube.
