### ISSUE TITLE
Correct voltages readings for a 2S internal battery.

### ISSUE THREAD

**Issue by bsdshneg** [qba667/FlySkyI6#55]
After the power improvements, namely the replacement of the stabilizers 6206a by ams1117 and the installation of the 2S lithium-ion battery, the maximum display voltage of the inner battery is equal to 6.65V. I understand that this reading of the values from the analog port is registered in the firmware. Tell me, is it possible to have another version of the firmware taking into account the work from the 2S lithium battery?
Thanks!

**Comment by qba667** [comment]
@bsdshneg
Replacing stabilizers was not necessary.
What you need to do is replacing resistors R9 and R10 - creating voltage divider for analog input of MCU.
Voltage calibration can be made in factory menu (sticks moved to left down before switching on the unit).
I have used 4.1k as R10 and 10K as R9.
![img_20180305_224001](https://user-images.githubusercontent.com/3341647/37001767-e38ebef2-20c7-11e8-9a7e-7149768842dc.jpg)

**Comment by bsdshneg** [comment]
Thank you!
But stabilizers 6206 up to 6v and 2s li-ion is 8.4v.

**Comment by qba667** [comment]
@bsdshneg 
you are correct - but it is strange that your unit contains 6206 - mine contains 9 V tolerant regulators (don't remember symbol).

**Comment by bsdshneg** [comment]
Maybe different revision ...
Thank you for resistors nominals )))

Still a question, time speech about it has come. How did you put the 2S battery? What kind of battery was used?

**Comment by qba667** [comment]
@bsdshneg 18650 after removing original battery holder will fit. 
![img_20180307_174610](https://user-images.githubusercontent.com/3341647/37105724-34b7bd1a-2230-11e8-92d5-80eef6dab6a1.jpg)
![img_20180307_174735](https://user-images.githubusercontent.com/3341647/37105725-34db2e6c-2230-11e8-9504-670274ad185b.jpg)
