### ISSUE TITLE
Failsafe isn't applied to sbus

### ISSUE THREAD

**Issue by supermomme** [qba667/FlySkyI6#62]
I use a modded FlySky I6 with a X6B use the ibus output for sbus.
It works all fine, but if i turn off the reciever the channels go all to "default" positions.
_Throttel: 850 (I don't know why)
Yaw,Pitch,Roll: 1500
The Aux channels freeze.

And i can't use rssi/snr for Failsafe, because the aux channels freeze.

With the PPM Port the failsafe is applied and works fine.

Can anyone help me? I like to fly with more than 8 Channels.

**Comment by qba667** [comment]
@supermomme as far as I know that is bug in receiver - updating firmware of X6B may help. Fail safe should be working also on IBUS, have you tried that?

**Comment by supermomme** [comment]
My Flight Controller doesn't accept ibus from the reciever. I don't know if my flight controller is bad or the reciever.

Where can i find the Firmware for the X6B?

**Comment by supermomme** [comment]
Is it that? [povlhp/FlySkyRxFirmware](https://github.com/povlhp/FlySkyRxFirmware)

**Comment by qba667** [comment]
@supermomme yes that is correct repository, but I am not able to confirm that newer FW will fix the issue.

**Comment by supermomme** [comment]
I'll try that.

**Comment by supermomme** [comment]
I think i flashed it now, but I don't know how to verify it.
Still no failsafe on sbus :/
Do you have any other suggestions for what i can do?

**Comment by supermomme** [comment]
closed due to no response

**Comment by qba667** [comment]
@supermomme try different firmware for example from IA6B. SBUS issues are known...

**Comment by supermomme** [comment]
Yeah i tried it with the IA6B firmware and it works on ibus but not on sbus. Thanks a lot thats what i want.
