### ISSUE TITLE
Unable to disable throttle hold

### ISSUE THREAD

**Issue by JonathanvanCaloen** [qba667/FlySkyI6#66]
When i disable throttle hold it shows "Hold OFF" but when i flip the switch it still changes the throttle

**Comment by Yenya** [comment]
@JonathanvanCaloen, can you verify that this happens also in the latest 1.7.6 release? Also verify that you don't have the same switch assigned to any other function (Teacher or Throttle curve come to mind). Thanks,

-Yenya

**Comment by acruise** [comment]
I had this problem too, it turned out I had Trainer mode turned on and set to SwD as well. I disabled Trainer mode, and the unwanted throttle hold also stopped. :)

**Comment by JonathanvanCaloen** [comment]
that fixed it, thanks!
