### ISSUE TITLE
Ok button hold bug, failsafe 5 second bug, and 20kb upload error bug

### ISSUE THREAD

**Issue by panoramastudio** [qba667/FlySkyI6#67]
![cbihr7s7hkk](https://user-images.githubusercontent.com/16818109/44944612-01910080-adeb-11e8-960a-f18684497f58.jpg)
1)when i go to menu->system->extra->timer, and hold OK button it shows 0 channel witch is not correct channel and does not exist, i think we need to rewrite this function 
2)failsave  work only when the rx and tx works with each other more than 5 seconds, in original it works emidietly

3)many many times load stops here-
![image](https://user-images.githubusercontent.com/16818109/44944625-28e7cd80-adeb-11e8-90e2-3816e8d37a2f.png)

**Comment by qba667** [comment]
@panoramastudio have you solved those issues? 
I think first one is because too generic implementation.
Fails safe must be checked, there should be no changes in this area.

**Comment by panoramastudio** [comment]
After it radio have no any  functionality, it does not turn on, than I tried to flash it with USB->UART of Arduino MEGA, and it flashed, all ok!
