### ISSUE TITLE
IBUS/SBUS

### ISSUE THREAD

**Issue by panoramastudio** [qba667/FlySkyI6#68]
How can I set it up to output ibus or sbus  with receiver? What receiver do I need for sbus?
What IDE do I need to change and recompile files?

**Comment by qba667** [comment]
@panoramastudio The GNU Arm Embedded Toolchain is necessary. SBUS/IBUS can be changes in Radio setup, RX output if I remember correctly.

**Comment by qba667** [comment]
@panoramastudio IA6B X6B should be fine - any questions more?
