### ISSUE TITLE
Tx Battery Status

### ISSUE THREAD

**Issue by tictac80** [qba667/FlySkyI6#69]
It was noted that the TX BATTERY VOLTAGE on the display is not as intuitive as the original BATTERY SYMBOL. Since the symbol requires more space to program, I would suggest a BATTERY PERCENTAGE be displayed instead of the actual voltage.

**Comment by liguo-git** [comment]
% more intuitive

**Comment by qba667** [comment]
@tictac80, that can be done there is enough space in main screen method to do so.

**Comment by DusanF** [comment]
I don't think it is a good idea. To display it correctly, you would need discharge curve for every battery type that is usable (Alcaline, Ni-XX, Li-XX) and calculate percentage from it

**Comment by DusanF** [comment]
I don't think it is a good idea. To display it correctly, you would need
discharge curve for every battery type that is usable (Alcaline, Ni-XX,
Li-XX) and calculate percentage from it

po 22. 10. 2018 o 9:27 Jakub <notifications@github.com> napísal(a):

**Comment by destarita** [comment]
9y99no9no

**Comment by Yenya** [comment]
I think the current firmware is OK without the battery icon - the primary source of the information about the empty battery should be the battery alarm - people do not have time to look at the screen when flying. And for the exact value one would need to know the battery type and discharge curve, as @DusanF said. So I think the current state of things is OK.
