### ISSUE TITLE
6 position rotary switch E

### ISSUE THREAD

**Issue by matarum** [qba667/FlySkyI6#7]
HI,

I was wondering if there is some kind of way to have a 6 position switch configured on switch E implementation. It could be useful in pixhawk projects.

Thanks

**Comment by qba667** [comment]
@matarum unfortunately not but you can use SwC (can be configured in extra menu) as 6 position switch and them use 2 position switch in place of SwC.

**Comment by matarum** [comment]
Sorry, I'm not sure I understand.
i can replace the 3 position switch with a 6 position switch on SwC (and configure it as variable in extra menu). Then I could replace 2 position switch with 3 position switch I removed from SwC on SwB and then put that 2 position switch on SwE?
is it right?

**Comment by qba667** [comment]
@matarum, yes this is absolutely right.

**Comment by matarum** [comment]
could I use a potentiometer instead of 6 pos switch on SwC?

**Comment by matarum** [comment]
ok. got it.
