### ISSUE TITLE
Flit10 rx does not bind

### ISSUE THREAD

**Issue by Tschazza** [qba667/FlySkyI6#76]
I made an update on the 14CH mod firmware and rebound all my quads, but I figured out, that its not possible to rebind to the flit10 rx. a8s and x6b bound immediately. Did I miss sth.? Is this a known issue?

**Comment by qba667** [comment]
@Tschazza hard to say, they should be compatible, what version are you using?

**Comment by Tschazza** [comment]
It worked now ... after a few tries.
