### ISSUE TITLE
Continuous alarm 

### ISSUE THREAD

**Issue by Dredan72** [qba667/FlySkyI6#77]
How do I silence the the alarm after flashing the 1.7.5 final with 8 channel ppm. The alarm start ringing immediately after flashing complete.

**Comment by qba667** [comment]
Probably it reuse already initialized memory - please check timer settings ("System->Extra->Timer"), alarm settings (System->Extra->Alarm), Tx Bat (system->Extra->Tx Bat). And RX battery it will be one of them.

**Comment by Dredan72** [comment]
Thanks. Will Check THAT.

**Comment by Dredan72** [comment]
Thank you so much. It worked. Problem was one of the alarms. 
I wanted to use channel 7 for dji naza flight mode with 3 position switch. I am stuck now. I tried going to the extra menu to fiddle with end points and could make it work.
