### ISSUE TITLE
Latency, Failsafe

### ISSUE THREAD

**Issue by HarutyunGazyan** [qba667/FlySkyI6#79]
Hi, do the latency of this firmware is bigger than the original one?
And about filesafe, after turning radio on,  it need several seconds to make filesafe work, so if I turn radio on, and I change stick position, and turn off the radio immediately, receiver do not get filesafe, and servo continues to hold previous stick position, if I turn on radio, and change stick position, and wait about 10 sec, and turn off, receiver gets the filesafe, and servo goes into filesafe default position, and do not hold old stick position as it happens in the first case.

**Comment by Yenya** [comment]
@HarutyunGazyan, I am not aware of this firmware having a bigger latency than the stock one.

As for the failsafe - could you test it again with 1.7.6?

**Comment by Yenya** [comment]
It has been NEEDINFO for several months now without response, so I am closing this. As I read the original report, it could be related to #94.
