### ISSUE TITLE
Switch D bug

### ISSUE THREAD

**Issue by Gonnir** [qba667/FlySkyI6#86]
I use an Eachine i6 (rebranded Flysky i6) with Flyplus 1.7.5. It worked fine for a few months but now if i flip down the switch D,  the first 4 channels are goes to the midpoint, making a flyaway or instant crash even if i do not assign anything to that switch. Affects all models on the transmitter. A factory reset and reflash helps, but only for a few uses and the bug comes back.

**Comment by 1074748905** [comment]
switch on the trainer mode will make this happen

**Comment by Gonnir** [comment]
Ooooh. Thanks! Everything works again. I tought that's a /model thing.
