### ISSUE TITLE
volume control

### ISSUE THREAD

**Issue by matarum** [qba667/FlySkyI6#9]
theres no way to lower or cut beeper's volume? sometimes i do tests on configuration when my family is sleeping, and fs-i6 is so noisy

**Comment by qba667** [comment]
@matarum - it can not be handled by software but it can be done by using variable resistance on buzzer circuit.

**Comment by matarum** [comment]
So it needs to be desoldered. Maybe i can put an  earphone plug with a switch

**Comment by JonasCz** [comment]
Or you can open the radio up and put a piece of tape over the buzzer hole - it will reduce the volume by a lot.
