### ISSUE TITLE
which receiver can support 14 channel ？

### ISSUE THREAD

**Issue by 1074748905** [qba667/FlySkyI6#91]
i have a iA6b receiver，Can iA6b receiver(without flashing other firmware )and fs-i6 with 1.75 firmware support 14 channel ？
when using ibus or sbus or ppm , is it always supportting 14channel?

**Comment by qba667** [comment]
Yes it should always send 14 channels over IBUS. Any receiver using IBUS port should be able to handle it.

**Comment by Yenya** [comment]
@1074748905 - 14 channels work only on digital output channels (IBUS/SBUS), not on PPM.

Closing, as this is not an issue.
