### ISSUE TITLE
"Extra" menu items missing for AFHDS models.

### ISSUE THREAD

**Issue by marktbaldridge** [qba667/FlySkyI6#93]
If a model is AFHDS not AFHDS 2A, some of the "Extra" menu items are missing. Only the Timer exists. I can workaround by switching to an AFHDS 2A model, changing the "Tx Bat" settings for instance, and then switching back. But this should be fixed. Not sure if this project is alive any more. Would be interested in contributing.
![photo_2020-04-28_22-52-57](https://user-images.githubusercontent.com/1854976/80603571-3ad1a780-89f6-11ea-93d2-f458adcef583.jpg)

**Comment by qba667** [comment]
There is bugfix version release coming soon - maybe I can address it as well.

**Comment by marktbaldridge** [comment]
Wonderful! I'm glad the project is still alive! I've made a small donation. :)

**Comment by qba667** [comment]
@marktbaldridge thanks, it was not necessary, during coming weekend I want to address few topic on this old project. Stay tuned - there is no much space for changes but some fixes will be done:)

**Comment by qba667** [comment]
[fs-i6_updater_05_02_15_23.zip](https://github.com/qba667/FlySkyI6/files/4567783/fs-i6_updater_05_02_15_23.zip)
Please try this one out.

**Comment by marktbaldridge** [comment]
That fixed it! Thank you so much!! I believe I will be using this firmware permanently now!
